# Generated by Django 3.0.5 on 2020-04-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='계약 종료일'),
        ),
        migrations.AddField(
            model_name='room',
            name='contract_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='최소 계약기간'),
        ),
        migrations.AddField(
            model_name='room',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='계약 시작일'),
        ),
        migrations.AddField(
            model_name='room',
            name='contract_type',
            field=models.IntegerField(choices=[(0, 'Minimal'), (1, 'Fixed')], default=0, verbose_name='계약 종류'),
        ),
        migrations.AddField(
            model_name='room',
            name='move_date',
            field=models.DateField(blank=True, null=True, verbose_name='입주 날짜'),
        ),
        migrations.AddField(
            model_name='room',
            name='move_direct',
            field=models.BooleanField(default=False, verbose_name='입주 즉시 가능 여부'),
        ),
    ]
