# Generated by Django 3.0.5 on 2020-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='rooms.Keyword'),
        ),
    ]
